name: Build and test
on:
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "Cargo.*"
      - ".github/workflows/*"
  push:
    branches: [main]
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Add wasm32-wasi and clippy
        run: |
          rustup target add wasm32-wasi
          rustup component add clippy
      - uses: wasmcloud/common-actions/install-wash@main
      - name: Install wasi-sdk
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/wasi-sdk-17.0-linux.tar.gz
          tar xzvf wasi-sdk-17.0-linux.tar.gz
          echo "PATH=$(pwd)/wasi-sdk-17.0/bin:${PATH}" >> $GITHUB_ENV
          echo "TARGET_CFLAGS=-I $(pwd)/wasi-sdk-17.0/share/wasi-sysroot/include/" >> $GITHUB_ENV
          echo "CC=$(pwd)/wasi-sdk-17.0/bin/clang" >> $GITHUB_ENV
      - name: Check formatting
        run: cargo fmt -- --check
        shell: bash
      - name: Build actor
        run: wash build
      - name: Check lints with clippy
        run: cargo clippy
